name: tdlogistic_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.9.0
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  flutter_webrtc: ^0.11.7
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  web_socket_channel: ^3.0.1
  jwt_decoder: ^2.0.1
  qr_code_scanner: ^1.0.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.3
  socket_io_client: ^3.0.0
  archive: ^3.6.1
  permission_handler: ^11.3.1
  mime: ^2.0.0
  dio: ^5.7.0
  http_parser: ^4.0.2
  path_provider: ^2.1.4
  dvhcvn: ^2.0.20240901
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/done.png
    - lib/assets/
